# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47f4564947fe916ad75efd9a36ff6826d802c7007eed775f2de5608d0ce5c61a7b1cf8014807b195fbc1e156c9c302e950689ac16b525436eb4bd1ab2c035308

test:
  secret_key_base: 24d240a668a92a5faa7a48407ac1759e48168d9d7e51324f12ad0ad3779746ae7054d569f87349a68a312da1b4ecd31a8d2b021d955cb01c7b890d324f689807

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
